set_property SEVERITY {Warning} [get_drc_checks LUTLP-1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE

set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 1000000000 -waveform {0 500000000} [get_ports clk]

set_property PACKAGE_PIN W7 [get_ports {LED_out[6]}]
set_property PACKAGE_PIN W6 [get_ports {LED_out[5]}]
set_property PACKAGE_PIN U8 [get_ports {LED_out[4]}]
set_property PACKAGE_PIN V8 [get_ports {LED_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {LED_out[2]}]
set_property PACKAGE_PIN V5 [get_ports {LED_out[1]}]
set_property PACKAGE_PIN U7 [get_ports {LED_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[0]}]
set_property PACKAGE_PIN R2 [get_ports {producto[15]}]
set_property PACKAGE_PIN T1 [get_ports {producto[14]}]
set_property PACKAGE_PIN U1 [get_ports {producto[13]}]
set_property PACKAGE_PIN W2 [get_ports {producto[12]}]
set_property PACKAGE_PIN R3 [get_ports {producto[11]}]
set_property PACKAGE_PIN T2 [get_ports {producto[10]}]
set_property PACKAGE_PIN T3 [get_ports {producto[9]}]
set_property PACKAGE_PIN V2 [get_ports {producto[8]}]
set_property PACKAGE_PIN W13 [get_ports {producto[7]}]
set_property PACKAGE_PIN W14 [get_ports {producto[6]}]
set_property PACKAGE_PIN V15 [get_ports {producto[5]}]
set_property PACKAGE_PIN W15 [get_ports {producto[4]}]
set_property PACKAGE_PIN W17 [get_ports {producto[3]}]
set_property PACKAGE_PIN W16 [get_ports {producto[2]}]
set_property PACKAGE_PIN V16 [get_ports {producto[1]}]
set_property PACKAGE_PIN V17 [get_ports {producto[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {producto[0]}]

set_property PACKAGE_PIN U2 [get_ports d0]
set_property PACKAGE_PIN U4 [get_ports d1]
set_property PACKAGE_PIN V4 [get_ports d2]
set_property PACKAGE_PIN W4 [get_ports d3]
set_property PACKAGE_PIN T17 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports d0]
set_property IOSTANDARD LVCMOS33 [get_ports d1]
set_property IOSTANDARD LVCMOS33 [get_ports d2]
set_property IOSTANDARD LVCMOS33 [get_ports d3]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
